### ISSUE TITLE
🥇 

### ISSUE THREAD

**Issue by norkator** [SKR301/The-Crypter#13]
Sweeeeet

**Comment by SKR301** [comment]
LOL

**Comment by norkator** [comment]
![Uploading Screenshot_20211003-234135_Chrome.jpg…]()

**Comment by norkator** [comment]
![Screenshot_20211003-234135_Chrome](https://user-images.githubusercontent.com/55850510/135770850-982346a7-49f1-4725-8f67-7f3c3a262503.jpg)

**Comment by SKR301** [comment]
Just curious...
How do you revoke collaborators access?
Nothing against you, really!
:D

**Comment by norkator** [comment]
> Just curious... How do you revoke collaborators access? Nothing against you, really! :D

![Screenshot_20211004-075140_Chrome](https://user-images.githubusercontent.com/55850510/135796164-12fbc409-0f92-4bce-aa1a-868683f19944.jpg)

**Comment by SKR301** [comment]
Gonna report you for "TOO MUCH SOUTH PARK REFERENCES"!!

![image](https://user-images.githubusercontent.com/47807051/135903254-0ed11b1f-9a3d-4a51-9f76-89ddea7afe43.png)

**Comment by norkator** [comment]
> Gonna report you for "TOO MUCH SOUTH PARK REFERENCES"!!
> 
> ![image](https://user-images.githubusercontent.com/47807051/135903254-0ed11b1f-9a3d-4a51-9f76-89ddea7afe43.png)

![Screenshot_20211004-221926_Chrome](https://user-images.githubusercontent.com/55850510/135911296-64c46c82-c1e0-49d7-91d4-e2e93b119194.jpg)

**Comment by norkator** [comment]
> You are lucky I'm not "Skank Hunk"... Otherwise jim carrey would have something extra in his mouth

I think I have idea what feature you talk about

![Screenshot_20211004-221926_Chrome](https://user-images.githubusercontent.com/55850510/136177984-da3a10bb-7a88-4e75-9af2-cb69cc193496.jpg)

**Comment by SKR301** [comment]
> 
> 
> ![Screenshot 2021-10-06 at 19 26 37](https://user-images.githubusercontent.com/55850510/136244763-498082dd-7c32-4c6d-925f-0aec532ebf1e.png)

O(n!)

**Comment by norkator** [comment]
Closing due racism
